### ISSUE TITLE
install_standard option does not work on squeeze/oldstable

### ISSUE THREAD

**Issue by myhro** [andsens/bootstrap-vz#144]
I was trying to reproduce [this grub error](https://github.com/andsens/bootstrap-vz/issues/122#issue-37736340), when an unrelated issue was raised:

    Adding standard packages from tasksel
    Executing: chroot /target/f76d3ce9/root tasksel --task-packages standard
    ~pstandard
    ~prequired
    ~pimportant
    Upgrading packages and fixing broken dependencies
    Executing: chroot /target/f76d3ce9/root apt-get install --fix-broken --no-install-recommends --assume-yes
    Reading package lists...
    Building dependency tree...
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Executing: chroot /target/f76d3ce9/root apt-get upgrade --no-install-recommends --assume-yes
    Reading package lists...
    Building dependency tree...
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Installing packages
    Executing: chroot /target/f76d3ce9/root apt-get install --no-install-recommends --assume-yes openssh-server linux-image-amd64 grub-pc sudo nfs-client ~pstandard ~prequired ~pimportant
    Reading package lists...
    Building dependency tree...
    E: Unable to locate package ~pstandard
    E: Unable to locate package ~prequired
    E: Unable to locate package ~pimportant
    apt exited with status code 100. This can sometimes occur when package retrieval times out or a package extraction failed. apt might succeed if you try bootstrapping again.
    Command 'chroot /target/f76d3ce9/root apt-get install --no-install-recommends --assume-yes openssh-server linux-image-amd64 grub-pc sudo nfs-client ~pstandard ~prequired ~pimportant' returned non-zero exit status 100
    Traceback (most recent call last):
      File "/vagrant/bootstrapvz/base/main.py", line 109, in run
        tasklist.run(info=bootstrap_info, dry_run=dry_run)
      File "/vagrant/bootstrapvz/base/tasklist.py", line 38, in run
        task.run(info)
      File "/vagrant/bootstrapvz/common/tasks/packages.py", line 38, in run
        actions[package.__class__](info, batch)
      File "/vagrant/bootstrapvz/common/tasks/packages.py", line 73, in install_remote
        raise e
    CalledProcessError: Command 'chroot /target/f76d3ce9/root apt-get install --no-install-recommends --assume-yes openssh-server linux-image-amd64 grub-pc sudo nfs-client ~pstandard ~prequired ~pimportant' returned non-zero exit status 100

So, we can see that the `tasksel` behavior is different on `squeeze`/`oldstable`.

**Comment by myhro** [comment]
Obsolete since #280.
