### ISSUE TITLE
Development branch: Inline Credentials - directly in manifest files - don't work

### ISSUE THREAD

**Issue by pmorch** [andsens/bootstrap-vz#154]
If I try to put AWS credentials into the .yml files, it doesn't seem to work. But only on the development branch's .yml files. If i do the same thing in master's .json files, all is well. I end with errors like:

    ...
    Creating workspace
    Getting AWS credentials
    Caught exception reading instance data
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
        r = opener.open(req, timeout=timeout)
      File "/usr/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    HTTPError: HTTP Error 404: Not Found
    Unable to read instance data, giving up
    No ec2 credentials found, they must all be specified exclusively via environment variables or through the manifest.
    Traceback (most recent call last):
      File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
        tasklist.run(info=bootstrap_info, dry_run=dry_run)
      File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 38, in run
        task.run(info)
      File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 15, in run
        info.credentials = cls.get_credentials(info.manifest, keys)
      File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 42, in get_credentials
        raise RuntimeError(('No ec2 credentials found, they must all be specified '
    RuntimeError: No ec2 credentials found, they must all be specified exclusively via environment variables or through the manifest.
    Rolling back
    ....

Details in:
https://gist.github.com/pmorch/c3d6d8ae1f9847037627

I'm no expert on YAML files, so perhaps I've messed it up. I've tried entering credentials as both e.g. 

    access-key: "XXXXXXXXXXXXXXXXXXXX"

and without the dbl-quote chars

    access-key: XXXXXXXXXXXXXXXXXXXX

I got the exact same result. Oh, and of course I'm using real access-key and secret-key! :-) 

Putting the same keys in AWS_ACCESS_KEY and AWS_SECRET_KEY environment variables works fine.

**Comment by jszwedko** [comment]
@pmorch you need to uncomment the `credentials: ` line and indent your credentials to be nested under it.

**Comment by pmorch** [comment]
@jszwedko: I think you're probably right about that when looking at the [gist](https://gist.github.com/pmorch/c3d6d8ae1f9847037627). Man, how could I have missed that? Sorry. Closing issue.

**Comment by andsens** [comment]
Glad it's fixed.
> Man, how could I have missed that?

Because I've forgot to add `additional_properties: false` in quite a few places in the manifest schema. bootstrap-vz could have caught that otherwise, sorry about that.
