### ISSUE TITLE
Disabling getty processes task fails half the time

### ISSUE THREAD

**Issue by Rory-Finnegan** [andsens/bootstrap-vz#179]
Looks like there is a race condition in the Disabling getty processes task where it tries to edit `etc/inittab` before it gets created.  Only tested on the [latest development] (https://github.com/Rory-Finnegan/bootstrap-vz/commit/255f0624b49dbcf6cacccd3b2f1fa7c0cc2bcc8d)
```
Disabling getty processes
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "bootstrap-vz/bootstrapvz/base/tasklist.py", line 38, in run
    task.run(info)
  File "bootstrap-vz/bootstrapvz/common/tasks/boot.py", line 31, in run
    sed_i(inittab_path, '^' + tty1, '#' + tty1)
  File "bootstrap-vz/bootstrapvz/common/tools.py", line 62, in sed_i
    for line in fileinput.input(files=file_path, inplace=True):
  File "/usr/lib/python2.7/fileinput.py", line 253, in next
    line = self.readline()
  File "/usr/lib/python2.7/fileinput.py", line 322, in readline
    os.rename(self._filename, self._backupfilename)
OSError: [Errno 2] No such file or directory
Rolling back
```

**Comment by andsens** [comment]
Ah yes, you are correct. [According to the documentation](http://www.freedesktop.org/software/systemd/man/logind.conf.html#NAutoVTs=) setting `NAutoVTs` to 0 should do the job

**Comment by andsens** [comment]
I pushed a change to the `wip-integration-testing` branch, but I have a hard time verifying the fix [seeing how I am unable to boot the machine](https://github.com/andsens/bootstrap-vz/issues/155#issuecomment-68527847).
