### ISSUE TITLE
New issue with Admin user

### ISSUE THREAD

**Issue by srivasta** [andsens/bootstrap-vz#285]
Hi,

  I am seeing failures in my daily build jobs with opening the authorized_key file for append. 
```
Installing the public key for the admin user
[Errno 2] No such file or directory: '/scratch/sandbox/build/16f390ae/root/home/srivasta/.ssh/authorized_keys'
Traceback (most recent call last):
  File "/usr/local/src/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/usr/local/src/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/usr/local/src/bootstrap-vz/bootstrapvz/plugins/admin_user/tasks.py", line 88, in run
    with open(auth_keys_abs, 'a') as auth_keys_handle:
IOError: [Errno 2] No such file or directory: '/scratch/sandbox/build/16f390ae/root/home/srivasta/.ssh/authorized_keys'
Rolling back
```

  The open call looks fine (mode "a" should create a file is it does not exist, right?)

  Manoj

**Comment by andsens** [comment]
It was the `.ssh` dir that didn't exist :-/
