### ISSUE TITLE
No ec2 credentials found

### ISSUE THREAD

**Issue by utiliware** [andsens/bootstrap-vz#319]
Output from console below:

root@ip-172-31-34-119:~# bootstrap-vz/bootstrap-vz bootstrap-vz/manifests/examples/ec2/ebs-testing-amd64-pvm.yml 
Getting AWS credentials
Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
Unable to read instance data, giving up
No ec2 credentials found, they must all be specified exclusively via environment variables or through the manifest.
Traceback (most recent call last):
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 27, in run
    info.credentials = cls.get_credentials(info.manifest, keys)
  File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 56, in get_credentials
    raise RuntimeError(('No ec2 credentials found, they must all be specified '
RuntimeError: No ec2 credentials found, they must all be specified exclusively via environment variables or through the manifest.
Rolling back
Successfully completed rollback
Traceback (most recent call last):
  File "bootstrap-vz/bootstrap-vz", line 5, in <module>
    main()
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 29, in main
    dry_run=opts['--dry-run'])
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 27, in run
    info.credentials = cls.get_credentials(info.manifest, keys)
  File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 56, in get_credentials
    raise RuntimeError(('No ec2 credentials found, they must all be specified '
RuntimeError: No ec2 credentials found, they must all be specified exclusively via environment variables or through the manifest.
## // .yml file below

name: debian-{system.release}-{system.architecture}-{provider.virtualization}-{%Y}-{%m}-{%d}-ebs
provider:
  name: ec2
  virtualization: hvm
  enhanced_networking: simple
    credentials:
      access-key: xxxxxxx
      secret-key: xxxxxxxxx
  description: Debian {system.release} {system.architecture}
bootstrapper:
  workspace: /target
system:
  release: jessie
  architecture: amd64
  bootloader: extlinux
  charmap: UTF-8
  locale: en_US
  timezone: UTC
volume:
  backing: ebs
  partitions:
    type: none
    root:
      filesystem: ext4
      size: 8GiB
packages:
  mirror: http://cloudfront.debian.net/debian
plugins:
  cloud_init:
    metadata_sources: Ec2
    username: admin
//

I have changed my credentials many times but get same error. Any ideas?

**Comment by CMeza99** [comment]
Is this still an issue?

I think this is no longer relevant to the current version of bootstrap-vz. Close?

**Comment by andsens** [comment]
Yup, I'd say this is stale. Closing...
