### ISSUE TITLE
'BootstrapInformation' object has no attribute 'grub_config'

### ISSUE THREAD

**Issue by thepwagner** [andsens/bootstrap-vz#328]
Recent changes break builds with:
```
system:
  bootloader: extlinux
```

Stacktrace:
```
Traceback (most recent call last):
  File "/app/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/app/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/app/bootstrapvz/common/tasks/grub.py", line 284, in run
    info.grub_config['GRUB_CMDLINE_LINUX'].append('init=/bin/systemd')
AttributeError: 'BootstrapInformation' object has no attribute 'grub_config'
```

**Comment by andsens** [comment]
Sorry about that. Should work now, though I wouldn't recommend using extlinux with jessie. Right now there is no upgrade support for when a new kernel is installed, since the helper scripts were removed in that release.

bootstrap-vz should really just not allow selecting it.
