### ISSUE TITLE
growpart not available

### ISSUE THREAD

**Issue by vorlock** [andsens/bootstrap-vz#329]
Hi guys,

few days ago I build deb for 0.9.10 and during testing it (building new Jessie AMI from Stretch host) hit a problem:

```
Adjusting expand-root for growpart-workaround
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/share/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/usr/share/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/usr/share/bootstrap-vz/bootstrapvz/common/tasks/initd.py", line 80, in run  
    sed_i(script, '^growpart="growpart"$', 'growpart-workaround')
  File "/usr/share/bootstrap-vz/bootstrapvz/common/tools.py", line 68, in sed_i
    replacement_count = inline_replace(file_path, pattern, subst)
  File "/usr/share/bootstrap-vz/bootstrapvz/common/tools.py", line 82, in inline_replace
    for line in fileinput.input(files=file_path, inplace=True):
  File "/usr/lib/python2.7/fileinput.py", line 237, in next
    line = self._readline()
  File "/usr/lib/python2.7/fileinput.py", line 316, in _readline
    os.rename(self._filename, self._backupfilename)
OSError: [Errno 2] No such file or directory
Press Enter to commence rollback
Rolling back
Tasklist:
        bootstrapvz.common.tasks.filesystem.UnmountRoot
        bootstrapvz.common.tasks.volume.Detach
        bootstrapvz.common.tasks.filesystem.DeleteMountDir
        bootstrapvz.common.tasks.volume.Delete
        bootstrapvz.common.tasks.workspace.DeleteWorkspace
```

I've identified from where it came from (I didn't fix it though) but then another question rose on my mind. We're using embedded copy of `growpart` in bootstrap-vz is there any specific reason for this when it can be installed with `cloud-guest-utils`?
Please keep in mind that I didn't do any comparison of the `growpart` between what is in bootstrap-vz and what comes from `cloud-guest-utils`

Also are we not lacking `growpart-workaround` script as I see that we're trying to use it but I can't find it anywhere.

**Comment by vorlock** [comment]
Line causing issues is this one https://github.com/andsens/bootstrap-vz/blob/master/bootstrapvz/plugins/cloud_init/__init__.py#L35
Commenting out this line is allowing to create AWS AMI with no issues.

**Comment by vorlock** [comment]
All sorted.
