### ISSUE TITLE
Unable to upload AMI on S3 (error (InvalidRequest): The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256)

### ISSUE THREAD

**Issue by unixfox** [andsens/bootstrap-vz#337]
Hi !

I've an issue, bootstrap an AMI on AWS EBS is working but when I try to bootstrap an AMI on AWS S3, euca2ools returns me an error:
````
Uploading the image bundle
euca-upload-bundle: error (InvalidRequest): The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
Command 'euca-upload-bundle --bucket aresrpg --manifest /target/3a1bf8f2/bundle-3a1bf8f2/debian-jessie-amd64-pvm-160826.manifest.xml --access-key xxxx --secret-key xxx --url https://s3-eu-central-1.amazonaws.com/ --region eu-central-1' returned non-zero exit status 1
Traceback (most recent call last):
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/ami.py", line 74, in run
    '--region', info._ec2['region']])
  File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 13, in log_check_call
    raise e
CalledProcessError: Command 'euca-upload-bundle --bucket aresrpg --manifest /target/3a1bf8f2/bundle-3a1bf8f2/debian-jessie-amd64-pvm-160826.manifest.xml --access-key xxx --secret-key xxxxx --url https://s3-eu-central-1.amazonaws.com/ --region eu-central-1' returned non-zero exit status 1
Rolling back
````

Did I made a **mistake** ? I don't really understand how to find the `private key` (`private-key:`) and `certificate` (`certificate:`).

Here is my manifest file:
````
---
name: debian-{system.release}-{system.architecture}-{provider.virtualization}-{%y}{%m}{%d}
provider:
  name: ec2
  virtualization: pvm
  credentials:
    access-key: xxxx
    secret-key: xxxx
    user-id: arn:aws:iam::123456789012:user/iamuser
    certificate: /tmp/server.cert
    private-key: /tmp/server.key
  description: Debian {system.release} {system.architecture}
  region: eu-central-1
  bucket: aresrpg
bootstrapper:
  workspace: /target
system:
  release: jessie
  architecture: amd64
  bootloader: pvgrub
  charmap: UTF-8
  locale: en_US
  timezone: Europe/Paris
volume:
  backing: s3
  partitions:
    type: none
    root:
      filesystem: ext4
      size: 4GiB
packages:
  mirror: http://cloudfront.debian.net/debian
  components:
  - main
  - contrib
  - non-free
  preferences:
    backport-cloud-init-cloud-utils:
    - package: cloud-init cloud-utils
      pin: release n=jessie-backports
      pin-priority: 500
  install:
  - awscli
  - python-boto
  - python3-boto
  - apt-transport-https
  - lvm2
  - ncurses-term
  - parted
  - cloud-init
  - cloud-utils
  - gdisk
  - systemd
  - systemd-sysv
plugins:
  cloud_init:
    metadata_sources: Ec2
    username: admin
    enable_modules:
      cloud_init_modules:
      - { module: growpart, position: 4}
````

**Comment by unixfox** [comment]
It's related to this issue : https://github.com/boto/boto/issues/2741
I think bootstrap-vz can't do anything, please close this issue if nobody can provide a solution.

**Comment by andsens** [comment]
Yup, definitely an issue with boto. I can't do much about that. Closing.
