### ISSUE TITLE
growpart broken on "huge" disks

### ISSUE THREAD

**Issue by xpender** [andsens/bootstrap-vz#359]
I just found that growpart fails on offical as also on custom built EC2 AMIs. I tried it with  ami-5900cc36 (8.7 / HVM / eu-central-1)

It seems depending on the disk size. With 30 GB it works fine, using bigger disks f.e. 500 GB it's broken. As I saw there are some growpart workarounds implemented in bootstrap-vz im not sure if this is a upstream bug or not?

growpart-workaround -v /dev/xvda 2

```
update-partition set to true
found GPT partition table (id = ee)
disk=/dev/xvda partition=2: original sgdisk info:
Partition GUID code: 0FC63DAF-8483-4772-8E79-3D69D8477DE4 (Linux filesystem)
Partition unique GUID: ACA4AF1D-5DBA-4DF3-8551-481F18DD9792
First sector: 2049 (at 1.0 MiB)
Last sector: 16777182 (at 8.0 GiB)
Partition size: 16775134 sectors (8.0 GiB)
Attribute flags: 0000000000000000
Partition name: 'root'
Disk /dev/xvda: 1048576000 sectors, 500.0 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): 29A6EC1C-58A8-4FFA-B403-63E11BDE5BC4
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 1048575966
Partitions will be aligned on 8-sector boundaries
Total free space is 1031798784 sectors (492.0 GiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              34            2048   1007.5 KiB  EF02  primary
   2            2049        16777182   8.0 GiB     8300  root
disk=/dev/xvda partition=2: pretend sgdisk info
Disk /dev/xvda: 1048576000 sectors, 500.0 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): 29A6EC1C-58A8-4FFA-B403-63E11BDE5BC4
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 1048575966
Partitions will be aligned on 8-sector boundaries
Total free space is 1031798784 sectors (492.0 GiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              34            2048   1007.5 KiB  EF02  primary
   2            2049        16777182   8.0 GiB     8300  root
disk=/dev/xvda partition=2: pt_start=2049 pt_end=16777182 pt_size=16775133 pt_max=1048575966 last=1048575966
disk=/dev/xvda partition=2: code=0FC63DAF-8483-4772-8E79-3D69D8477DE4 guid=ACA4AF1D-5DBA-4DF3-8551-481F18DD9792 name='root'
failed [pt_update:1] pt_update /dev/xvda 2
partx: /dev/xvda: error updating partition 2
FAILED: disk=/dev/xvda partition=2: failed to repartition
***** WARNING: Resize failed, attempting to revert ******
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot.
The operation has completed successfully.
***** Appears to have gone OK ****
```

**Comment by vorlock** [comment]
I can confirm this on this specific AMI, more details below:

```
admin@ip-172-31-7-45:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda2      7.8G  824M  6.6G  11% /
udev             10M     0   10M   0% /dev
tmpfs           200M  4.2M  196M   3% /run
tmpfs           500M     0  500M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           500M     0  500M   0% /sys/fs/cgroup

root@ip-172-31-7-45:~# fdisk -l

Disk /dev/xvda: 1 TiB, 1099511627776 bytes, 2147483648 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 29A6EC1C-58A8-4FFA-B403-63E11BDE5BC4

Device     Start      End  Sectors    Size Type
/dev/xvda1    34     2048     2015 1007.5K BIOS boot
/dev/xvda2  2049 16777182 16775134      8G Linux filesystem
```

```
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f3cff381f60>)
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Reading from /proc/310/mountinfo (quiet=False)
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Read 2214 bytes from /proc/310/mountinfo
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Reading from /sys/class/block/xvda2/partition (quiet=False)
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda2/partition
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '2'] with allowed return codes [0] (shell=False, capture=True)
Jan 23 21:08:24 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Running command ['growpart', '/dev/xvda', '2'] with allowed return codes [0] (shell=False, capture=True)
Jan 23 21:08:26 ip-172-31-7-45 [CLOUDINIT] util.py[WARNING]: Failed: growpart /dev/xvda 2
Jan 23 21:08:26 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: Failed: growpart /dev/xvda 2#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py", line 109, in resize#012    util.subp(["growpart", diskdev, partnum])#012  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1684, in subp#012    cmd=args)#012cloudinit.util.ProcessExecutionError: Unexpected error while running command.#012Command: ['growpart', '/dev/xvda', '2']#012Exit code: 2#012Reason: -#012Stdout: "FAILED: disk=/dev/xvda partition=2: failed to repartition\nWarning! Current disk size doesn't match that of the backup!\nAdjusting sizes to match, but subsequent problems are possible!\nWarning: The kernel is still using the old partition table.\nThe new table will be used at the next reboot.\nThe operation has completed successfully.\n"#012Stderr: 'failed [pt_update:1] pt_update /dev/xvda 2\npartx: /dev/xvda: error updating partition 2\n***** WARNING: Resize failed, attempting to revert ******\n***** Appears to have gone OK ****\n'
Jan 23 21:08:26 ip-172-31-7-45 [CLOUDINIT] util.py[DEBUG]: resize_devices took 2.526 seconds
Jan 23 21:08:26 ip-172-31-7-45 [CLOUDINIT] cc_growpart.py[DEBUG]: '/' FAILED: failed to resize: disk=/dev/xvda, ptnum=2: Unexpected error while running command.#012Command: ['growpart', '/dev/xvda', '2']#012Exit code: 2#012Reason: -#012Stdout: "FAILED: disk=/dev/xvda partition=2: failed to repartition\nWarning! Current disk size doesn't match that of the backup!\nAdjusting sizes to match, but subsequent problems are possible!\nWarning: The kernel is still using the old partition table.\nThe new table will be used at the next reboot.\nThe operation has completed successfully.\n"#012Stderr: 'failed [pt_update:1] pt_update /dev/xvda 2\npartx: /dev/xvda: error updating partition 2\n***** WARNING: Resize failed, attempting to revert ******\n***** Appears to have gone OK ****\n'
```

**Comment by andsens** [comment]
definitely upstream, you should report this at the Debian bugtracker or write to the debian-cloud mailing list, they might have ideas for a fix. Feel free to re-open if there is some way to work around this without having to wait for upstream to implement and publish the fix.

**Comment by noqqe** [comment]
Experienced the same, disks with 250GB work.
