### ISSUE TITLE
Stretch/kvm fails with  for lack of generate-ssh-hostkeys

### ISSUE THREAD

**Issue by andrewbogott** [andsens/bootstrap-vz#376]
I ran into this with a custom manifest, but using the built in stretch-virtio-partitions.yml manifest I still can't build an image.  The build errors out with this traceback:

Traceback (most recent call last):
  File "/usr/local/bin/bootstrap-vz", line 9, in <module>
    load_entry_point('bootstrap-vz==0.9.11', 'console_scripts', 'bootstrap-vz')()
  File "/usr/local/lib/python2.7/dist-packages/bootstrap_vz-0.9.11-py2.7.egg/bootstrapvz/base/main.py", line 29, in main
    dry_run=opts['--dry-run'])
  File "/usr/local/lib/python2.7/dist-packages/bootstrap_vz-0.9.11-py2.7.egg/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/bootstrap_vz-0.9.11-py2.7.egg/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/usr/local/lib/python2.7/dist-packages/bootstrap_vz-0.9.11-py2.7.egg/bootstrapvz/common/tasks/initd.py", line 22, in run
    copy(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/bootstrap_vz-0.9.11-py2.7.egg/bootstrapvz/common/assets/init.d/generate-ssh-hostkeys'

**Comment by andrewbogott** [comment]
Indeed, common/assets doesn't seem to get installed at all by setup.py.

**Comment by andsens** [comment]
There, that should do it :-)
