### ISSUE TITLE
"No such file or directory" after mapping volume permissions

### ISSUE THREAD

**Issue by RX14** [andsens/bootstrap-vz#380]
```
bootstrap-vz/bootstrap-vz bootstrap-vz/manifests/official/ec2/ebs-jessie-amd64-hvm.yml
Generating tasklist
Adding commands required for bootstrapping Debian
Determining required external commands for EC2 bootstrapping
Adding commands required for formatting
Adding commands required for partitioning the volume
Checking availability of external commands
Adding openssh package
Creating workspace
Adding locale package to bootstrap installation
Initializing grub standard configuration
Adding default release sources
Adding backports to the apt sources
Adding cloud-init package and sudo
Retrieving instance metadata
Adding grub package
Getting AWS credentials
Connecting to EC2
Found credentials in environment variables.
Silence boto debug logging
Determining the AMI name
Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
Adding DKMS and kernel header packages
Adding packages from the manifest
Adding image packages required for EC2
Adding preferences from the manifest
Creating the EBS volume
Resetting dropped connection: ec2.us-east-1.amazonaws.com
Attaching the volume
Resetting dropped connection: ec2.us-east-1.amazonaws.com
Partitioning the volume
Mapping volume partitions
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/root/bootstrap-vz/bootstrapvz/common/tasks/partitioning.py", line 38, in run
    info.volume.partition_map.map(info.volume)
  File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 61, in map
    self.fsm.map(volume=volume)
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 286, in fn
    if self._before_event(e) is False:
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 321, in _before_event
    return getattr(self, fnname)(e)
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 89, in _callback
    return func(obj, *args, **kwargs)
  File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 70, in _before_map
    mappings = log_check_call(['kpartx', '-l', volume.device_path])
  File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 5, in log_check_call
    status, stdout, stderr = log_call(command, stdin, env, shell, cwd)
  File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 33, in log_call
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Rolling back
Detaching the volume
Resetting dropped connection: ec2.us-east-1.amazonaws.com
Deleting the volume
Deleting workspace
Successfully completed rollback
Traceback (most recent call last):
  File "bootstrap-vz/bootstrap-vz", line 5, in <module>
    main()
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 29, in main
    dry_run=opts['--dry-run'])
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/root/bootstrap-vz/bootstrapvz/common/tasks/partitioning.py", line 38, in run
    info.volume.partition_map.map(info.volume)
  File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 61, in map
    self.fsm.map(volume=volume)
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 286, in fn
    if self._before_event(e) is False:
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 321, in _before_event
    return getattr(self, fnname)(e)
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 89, in _callback
    return func(obj, *args, **kwargs)
  File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 70, in _before_map
    mappings = log_check_call(['kpartx', '-l', volume.device_path])
  File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 5, in log_check_call
    status, stdout, stderr = log_call(command, stdin, env, shell, cwd)
  File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 33, in log_call
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The debug log just around the error is this:

```
Mapping volume partitions
Executing: kpartx -l /dev/xvdf
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/root/bootstrap-vz/bootstrapvz/common/tasks/partitioning.py", line 38, in run
    info.volume.partition_map.map(info.volume)
  File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 61, in map
    self.fsm.map(volume=volume)
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 286, in fn
    if self._before_event(e) is False:
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 321, in _before_event
    return getattr(self, fnname)(e)
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 89, in _callback
    return func(obj, *args, **kwargs)
  File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 70, in _before_map
    mappings = log_check_call(['kpartx', '-l', volume.device_path])
  File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 5, in log_check_call
    status, stdout, stderr = log_call(command, stdin, env, shell, cwd)
  File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 33, in log_call
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Rolling back
```

**Comment by RX14** [comment]
After reading the error, I realised that kpartx wasn't installed. I must have skipped that part of the readme.

Sorry about this!

**Comment by andsens** [comment]
Don't be! This is actually a bug. bootstrap-vz should have failed much earlier when it said "Checking availability of external commands". The "Adding commands required for partitioning the volume" should have added "kpartx" to the list of required commands and the check should have failed when it went over the list.  
When kpartx is not installed on your system, what does `type kpartx; echo $?` output?

**Comment by RX14** [comment]
```
-bash: type: kpartx: not found
1
```

**Comment by andsens** [comment]
OK, this just baffles me. How the heck is your machine able to get past the check!?  
As per the log you get to [this task](https://github.com/andsens/bootstrap-vz/blob/9ac970b715698bc193ca08354ef109ac4d80f08c/bootstrapvz/common/tasks/partitioning.py#L8), which adds `kpartx` as a required command and then you get to [this task](https://github.com/andsens/bootstrap-vz/blob/9ac970b715698bc193ca08354ef109ac4d80f08c/bootstrapvz/common/tasks/host.py#L16), which runs through all external dependencies and fails, if the command you ran above returns non-zero... which it does, on your machine.  
If it is not too much trouble, could you link to a gist of the full debug output when the run fails?
