### ISSUE TITLE
ManifestError: 'qcow2' is not one of ['raw']

### ISSUE THREAD

**Issue by kevin-olbrich** [andsens/bootstrap-vz#401]
Hello,
I am unable to build "jessie-qcow2.yml" on bootstrap-vz @ deb stretch.
What am I missing?

```
root@slde0005:~# apt-show-versions bootstrap-vz
bootstrap-vz:all/stretch 0.9.10+20170110git-1 uptodate
root@slde0005:~# bootstrap-vz /tmp/build-sip/jessie-qcow2.yml
Traceback (most recent call last):
  File "/usr/bin/bootstrap-vz", line 11, in <module>
    load_entry_point('bootstrap-vz==0.9.10', 'console_scripts', 'bootstrap-vz')()
  File "/usr/share/bootstrap-vz/bootstrapvz/base/main.py", line 23, in main
    manifest = Manifest(path=opts['MANIFEST'])
  File "/usr/share/bootstrap-vz/bootstrapvz/base/manifest.py", line 35, in __init__
    self.validate()
  File "/usr/share/bootstrap-vz/bootstrapvz/base/manifest.py", line 92, in validate
    self.modules['provider'].validate_manifest(self.data, self.schema_validator, self.validation_error)
  File "/usr/share/bootstrap-vz/bootstrapvz/providers/kvm/__init__.py", line 8, in validate_manifest
    validator(data, rel_path(__file__, 'manifest-schema.yml'))
  File "/usr/share/bootstrap-vz/bootstrapvz/base/manifest.py", line 132, in schema_validator
    self.validation_error(e.message, e.path)
  File "/usr/share/bootstrap-vz/bootstrapvz/base/manifest.py", line 142, in validation_error
    raise ManifestError(message, self.path, data_path)
bootstrapvz.common.exceptions.ManifestError: 'qcow2' is not one of ['raw']
  File path: /tmp/build-sip/jessie-qcow2.yml
  Data path: volume.backing
```

**Comment by kevin-olbrich** [comment]
Seems like the release in stretch is too old.
Would be useful to stick to git revisions instead of releases downstrea at debian.

**Comment by andsens** [comment]
You should probably try with the latest master first. The one in apt is quite outdated. If the problem persists, make sure to post the manifest as well.

**Comment by kevin-olbrich** [comment]
Build with master ideed works (currently building).

**Comment by andsens** [comment]
Great! Closing.
