### ISSUE TITLE
missing bootstrapvz/providers/ec2/assets/cloud-init/debian_cloud.cfg

### ISSUE THREAD

**Issue by CMeza99** [andsens/bootstrap-vz#421]
```
Setting the grub terminal to `console'
Blacklisting unused kernel modules
Disabling the grub recovery menu entry
Configuring PVGrub
Setting the selected local timezone (link)
Setting cloud-init default mount options
[Errno 2] No such file or directory: '/root/venv/local/lib/python2.7/site-packages/bootstrapvz/providers/ec2/assets/cloud-init/debian_cloud.cfg'
Traceback (most recent call last):
  File "/root/venv/local/lib/python2.7/site-packages/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/venv/local/lib/python2.7/site-packages/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/root/venv/local/lib/python2.7/site-packages/bootstrapvz/providers/ec2/tasks/tuning.py", line 28, in run
    copy(cloud_init_src, cloud_init_dst)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/root/venv/local/lib/python2.7/site-packages/bootstrapvz/providers/ec2/assets/cloud-init/debian_cloud.cfg'```

**Comment by CMeza99** [comment]
not sure what happened. i think had done a `pip install bootstrap-vz`. now i installed from a `git clone` and `pip --upgrade`

**Comment by andsens** [comment]
Yeah, the pypi version is horribly outdated, I should really just remove it...
