### ISSUE TITLE
Failed to build Stretch

### ISSUE THREAD

**Issue by citypw** [andsens/bootstrap-vz#483]
root@mdebian:/home/debian/bootstrap-vz#  ./bootstrap-vz manifests/official/ec2/ebs-stretch-amd64-hvm.yml 
Generating tasklist
Adding commands required for bootstrapping Debian
Adding commands required for partitioning the volume
Adding commands required for formatting
Determining required external commands for EC2 bootstrapping
Checking availability of external commands
Adding openssh package
Adding image packages required for EC2
Getting AWS credentials
Starting new HTTP connection (1): 169.254.169.254
'NoneType' object has no attribute 'get_frozen_credentials'
Traceback (most recent call last):
  File "/home/debian/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/home/debian/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/home/debian/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 27, in run
    info.credentials = cls.get_credentials(info.manifest, keys)
  File "/home/debian/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 58, in get_credentials
    provider = Session(**provider_args).get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
Rolling back
Successfully completed rollback
Traceback (most recent call last):
  File "./bootstrap-vz", line 5, in <module>
    main()
  File "/home/debian/bootstrap-vz/bootstrapvz/base/main.py", line 29, in main
    dry_run=opts['--dry-run'])
  File "/home/debian/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/home/debian/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/home/debian/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 27, in run
    info.credentials = cls.get_credentials(info.manifest, keys)
  File "/home/debian/bootstrap-vz/bootstrapvz/providers/ec2/tasks/connection.py", line 58, in get_credentials
    provider = Session(**provider_args).get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'

**Comment by andsens** [comment]
Fixed in a4f2e1cfdb16ddfff346c222ab8a8579f6d8aa76
