### ISSUE TITLE
Support for buster

### ISSUE THREAD

**Issue by gbukovszki** [andsens/bootstrap-vz#490]
Guys,

buster is not supported, putting buster in the manifest:

`system:
  release: buster
`

results in:
`
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/share/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/usr/share/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/usr/share/bootstrap-vz/bootstrapvz/providers/virtualbox/tasks/packages.py", line 14, in run
    info.manifest.system['architecture']])
  File "/usr/share/bootstrap-vz/bootstrapvz/common/tools.py", line 117, in config_get
    config = config.get(key)
AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by kevin-olbrich** [comment]
I noticed the same für KVM but not yet had the time to check what’s wrong. In theory stretch and buster should not be much different.

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by andrewbogott** [comment]
I think that issue is resolved by

https://github.com/andsens/bootstrap-vz/pull/493

...that can't merge until we fix some linting issues though.
