### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by kevin-olbrich** [andsens/bootstrap-vz#498]
If I try to build a VM on a buster host, I receive this:

```
Adding image packages required for kvm
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/vm_image_build/project/imageconf/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/var/lib/jenkins/workspace/vm_image_build/project/imageconf/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
    task.run(info)
  File "/var/lib/jenkins/workspace/vm_image_build/project/imageconf/bootstrap-vz/bootstrapvz/providers/kvm/tasks/packages.py", line 14, in run
    info.manifest.system['architecture']])
  File "/var/lib/jenkins/workspace/vm_image_build/project/imageconf/bootstrap-vz/bootstrapvz/common/tools.py", line 118, in config_get
    config = config.get(key)
AttributeError: 'NoneType' object has no attribute 'get'
Rolling back
```

Manifest:
https://bitbucket.org/code-orange/thinclient-os/src/master/imageconf/vmtemplate.yml

**Comment by kevin-olbrich** [comment]
PS: Seems to be only a problem with i386.

**Comment by andsens** [comment]
hm, buster is defined in the [package kernel list](https://github.com/andsens/bootstrap-vz/blob/568f994367ac1b1f51ceef3f0e2a5cf69a2edd52/bootstrapvz/providers/kvm/tasks/packages-kernels.yml), though there could be some yaml parsing issue because amd64 is defined multiple times.

Try removing the duplicate `amd64` key in the yaml file.  
If that doesn't help I suggest inserting a `print('%s %s' % (info.manifest.release.codename, info.manifest.system['architecture']))` [before tries to get the package name](https://github.com/andsens/bootstrap-vz/blob/568f994367ac1b1f51ceef3f0e2a5cf69a2edd52/bootstrapvz/providers/kvm/tasks/packages.py#L13-L14) to see what is going on.

**Comment by kevin-olbrich** [comment]
Ouch, you are right. My jenkins pipeline had a wrong regex which resulted in skipping the submodule update for this one.

Thank you very much!
